name: 04. Inputs & Outputs

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      logLevel: ${{ steps.step1.outputs.logLevel }}
      tags: ${{ steps.step2.outputs.tags }}
      environment: ${{ steps.step3.outputs.environment }}
    steps:
      - id: step1
        run: echo "logLevel=${{ inputs.logLevel }}" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "tags=${{ inputs.tags }}" >> "$GITHUB_OUTPUT"
      - id: step3
        run: echo "environment=${{ inputs.environment }}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "${{needs.job1.outputs.logLevel}} ${{needs.job1.outputs.tags}} ${{needs.job1.outputs.environment}}"
