name: 05. Condition

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: true
        run: |
          exit 1
  job2:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: |
          exit 1
