name: 08. Custom Action Workflow

on:
  workflow_dispatch:
    inputs:
      job:
        type: choice
        options:
          - Composite_Action
          - Docker_Action
          - JavaScript_Action

jobs:
  composite-action:
    name: Composite Action
    if: ${{ inputs.job == 'Composite_Action' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Calculate Sum
        id: calculate-sum
        uses: ./.github/actions/composite
        with:
          first-number: 1
          second-number: 2
      - name: Print sum
        run: 'echo "Sum: ${{ steps.calculate-sum.outputs.sum }}"'

  docker-action:
    name: Docker Action
    if: ${{ inputs.job == 'Docker_Action' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Calculate Sum
        id: calculate-sum
        uses: ./.github/actions/docker
        with:
          first-number: 1
          second-number: 2
      - name: Print sum
        run: 'echo "Sum: ${{ steps.calculate-sum.outputs.sum }}"'

  javascript-action:
    name: JavaScript Action
    if: ${{ inputs.job == 'JavaScript_Action' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Calculate Sum
        id: calculate-sum
        uses: ./.github/actions/javascript
        with:
          first-number: 1
          second-number: 2
      - name: Print sum
        run: 'echo "Sum: ${{ steps.calculate-sum.outputs.sum }}"'
