name: Matrix Workflow

on: push

jobs:
  one-dimension-matrix:
    name: Java ${{ matrix.version }}
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        version: [ 8, 11, 17 ]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}
      - name: Check Java version
        run: java -version
