name: Matrix Workflow

on: push

jobs:
  one-dimension-matrix:
    name: Java ${{ matrix.version }}
    if: false
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        version: [ 8, 11, 17 ]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}
      - name: Check Java version
        run: java -version

  two-dimension-matrix:
    name: ${{ matrix.os }} - Java ${{ matrix.version }}
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        version: [ 8, 11, 17 ]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.version }}
      - name: Check Java version
        run: java -version

  fail-fast-matrix:
    name: ${{ matrix.os }} - Java ${{ matrix.version }}
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        version: [ 8, 11, 17 ]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.version }}
      - name: Fail job
        if: ${{ matrix.version == 11 }}
        run: exit 1
      - name: Check Java version
        run: java -version

  non-fail-fast-matrix:
    name: ${{ matrix.os }} - Java ${{ matrix.version }}
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        version: [ 8, 11, 17 ]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.version }}
      - name: Fail job
        if: ${{ matrix.version == 11 }}
        run: exit 1
      - name: Check Java version
        run: java -version

  parallel-matrix:
    name: ${{ matrix.os }} - Java ${{ matrix.version }}
    if: true
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        version: [ 8, 11, 17 ]
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.version }}
      - name: Check Java version
        run: java -version
